[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
fs_permissions = [
    { access = "read", path = "./test/bin" }
]
remappings = [
    "@forge-std/=dependencies/forge-std-1.9.7/src",
    "@uniswap-v4-core/=dependencies/uniswap-v4-core-4/src"
]

[dependencies]
forge-std = "1.9.7"
uniswap-v4-core = "4"

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
